apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrepository-grafana.yaml
  - grafana-auth-secret.yaml
  - dashboards/flux-apps-dashboard.yaml
  - helmrelease.yaml
  - loki.yaml
  - promtail.yaml
  - grafana-viewer-job.yaml
