apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Never
          env:
            - name: REDIS_HOST
              value: redis-0.redis
