# This file configures Flux to sync this cluster path from Git.
# Upgrade Flux controllers: run `flux install --export > gotk-components.yaml` and git push.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: main
  url: https://github.com/QuangNguyen1806/kubernetes-test.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 15s
  path: ./flux/clusters/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
