apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: intern-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: api2-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: api3-ns
