apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      serviceAccountName: fastapi-sa
      containers:
        - name: fastapi
          image: fastapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          env:
            - name: REDIS_HOST
              value: redis-0.redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: fastapi-ns
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 8000
      nodePort: 30080
