apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-secret-reader
  namespace: flux-intern-app
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-fastapi-sa-binding
  namespace: flux-intern-app
subjects:
  - kind: ServiceAccount
    name: fastapi-sa
    namespace: flux-fastapi-ns
roleRef:
  kind: Role
  name: config-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-api2-sa-binding
  namespace: flux-intern-app
subjects:
  - kind: ServiceAccount
    name: api2-sa
    namespace: flux-api2-ns
roleRef:
  kind: Role
  name: config-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-api3-sa-binding
  namespace: flux-intern-app
subjects:
  - kind: ServiceAccount
    name: api3-sa
    namespace: flux-api3-ns
roleRef:
  kind: Role
  name: config-secret-reader
  apiGroup: rbac.authorization.k8s.io
