apiVersion: apps/v1
kind: Deployment
metadata:
  name: api3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api3
  template:
    metadata:
      labels:
        app: api3
    spec:
      serviceAccountName: api3-sa
      containers:
        - name: api3
          image: api3:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          env:
            - name: REDIS_
              value: redis-0.redis.fastapi-ns.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_KEY
              value: api3:items
