apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api3-ns
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - rbac.yaml
configMapGenerator:
  - name: app-config
    literals:
      - APP_NAME=api3
      - MESSAGE=Hello from api3 ConfigMap
secretGenerator:
  - name: app-secret
    literals:
      - API_KEY=sk-api3-secret-key
  - name: redis-secret
    literals:
      - REDIS_PASSWORD=redis-super-secret-password
    options:
      disableNameSuffixHash: true
