apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/QuangNguyen1806/kubernetes-test.git
    targetRevision: main
    path: infrastructure/rbac/base
  destination:
    server: https://kubernetes.default.svc
    namespace: intern-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
