apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/QuangNguyen1806/kubernetes-test.git
    targetRevision: main
    path: infrastructure/redis/overlays/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
