#!/usr/bin/env bash
# Regenerate apps/flux-apps/kustomization.yaml from apps/*/overlays/flux.
# Add a Flux app by creating apps/<name>/overlays/flux/ only, then run this script.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/apps/flux-apps/kustomization.yaml"
mkdir -p "$ROOT/apps/flux-apps"

found=0
{
  echo "# GENERATED by scripts/generate-flux-apps.sh — do not edit by hand."
  echo "# Add an app: create apps/<name>/overlays/flux/ then re-run this script."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo "resources:"
  # Portable (macOS bash 3.2): no mapfile
  while IFS= read -r ks; do
    [[ -n "$ks" ]] || continue
    rel="${ks#"$ROOT"/apps/}"
    dir="$(dirname "$rel")"
    echo "  - ../${dir}"
    found=1
  done < <(find "$ROOT/apps" -path '*/overlays/flux/kustomization.yaml' | sort)
} > "$OUT"

if [[ "$found" -eq 0 ]]; then
  rm -f "$OUT"
  echo "ERROR: no apps/*/overlays/flux found" >&2
  exit 1
fi

echo "Wrote $OUT"
kubectl kustomize "$ROOT/apps/flux-apps" >/dev/null
echo "OK: flux-apps kustomize builds cleanly"
