apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api3
  labels:
    app: api3
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api3
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
